### ISSUE TITLE
How to disable route to exclusive url.

### ISSUE THREAD

**Issue by caiovncius** [alterfw/ampersand#15]
I am using ampersand in one project. I have a problem to access sitemap generated by Yoast. When try access the sitemap url, the ampersand bock, returning the 404 error.

How to I solve it?

**Comment by caiovncius** [comment]
any solution?

**Comment by sergiopvilar** [comment]
Can you give more details please?

**Comment by caiovncius** [comment]
I need access the native WordPress url.

**Comment by caiovncius** [comment]
I wish that when I received a specific url, example mydomain.com/sitemap.html, I could access this native Wordpress url. What happens is that when I use ampersand, native WordPress urls become inaccessible.

**Comment by sergiopvilar** [comment]
Fixed by #16.

**Comment by sergiopvilar** [comment]
```Route::ignore('/someurl')```
